name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  JAVA_VERSION: 17

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: "snyk/actions/gradle-jdk$JAVA_VERSION@master"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK $JAVA_VERSION
        uses: actions/setup-java@v1
        with:
          java-version: $JAVA_VERSION
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: build

  code-security:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: "snyk/actions/gradle-jdk$JAVA_VERSION@master"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
