name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  JAVA_VERSION: 17

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls

  dependencies-analysis:
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: "snyk/actions/gradle-jdk17@master"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: build

  code-security:
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: "snyk/actions/gradle-jdk17@master"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
